In [1]:
import numpy as np

In [11]:
R_WC = np.array([
    [0.83041423, 0.0085709, 0.16997286],
    [0.72704336, 0.77782549, 0.2303317],
    [0.46453981, 0.28336507, 0.43178532]
])
R_WC

array([[0.83041423, 0.0085709 , 0.16997286],
       [0.72704336, 0.77782549, 0.2303317 ],
       [0.46453981, 0.28336507, 0.43178532]])

In [8]:
# Define the angles in degrees
alpha_degrees = 30  # Rotation around X-axis
beta_degrees = 45   # Rotation around Y-axis
gamma_degrees = 60  # Rotation around Z-axis

# Convert angles to radians
alpha_radians = np.radians(alpha_degrees)
beta_radians = np.radians(beta_degrees)
gamma_radians = np.radians(gamma_degrees)

# Compute individual rotation matrices
R_x = np.array([
    [1, 0, 0],
    [0, np.cos(alpha_radians), -np.sin(alpha_radians)],
    [0, np.sin(alpha_radians), np.cos(alpha_radians)]
])

R_y = np.array([
    [np.cos(beta_radians), 0, np.sin(beta_radians)],
    [0, 1, 0],
    [-np.sin(beta_radians), 0, np.cos(beta_radians)]
])

R_z = np.array([
    [np.cos(gamma_radians), -np.sin(gamma_radians), 0],
    [np.sin(gamma_radians), np.cos(gamma_radians), 0],
    [0, 0, 1]
])

# Combine the rotation matrices
R_combined = np.dot(np.dot(R_z, R_y), R_x)

R_combined



array([[ 0.35355339, -0.5732233 ,  0.73919892],
       [ 0.61237244,  0.73919892,  0.28033009],
       [-0.70710678,  0.35355339,  0.61237244]])

In [9]:
def rotate_points_euler(angles):
    """
    Generate a composite rotation matrix from Euler angles.

    Parameters:
    - angles: Tuple of Euler angles (ax, ay, az) for rotation around the x, y, and z axes respectively.

    Returns:
    - R: The composite rotation matrix.
    """
    # Unpack the Euler angles
    ax, ay, az = np.radians(angles)

    # Rotation matrices around the x, y, and z axes
    # Your code here to define Rx, Ry, Rz
    Rx = np.array([[1, 0, 0],
                   [0, np.cos(ax), -np.sin(ax)],
                   [0, np.sin(ax), np.cos(ax)]])

    Ry = np.array([[np.cos(ay), 0, np.sin(ay)],
                   [0, 1, 0],
                   [-np.sin(ay), 0, np.cos(ay)]])

    Rz = np.array([[np.cos(az), -np.sin(az), 0],
                   [np.sin(az), np.cos(az), 0],
                   [0, 0, 1]])

    # Composite rotation matrix R
    # Hint: How do you combine Rx, Ry, Rz into a single rotation matrix?
    # Your code here
    R = np.dot(Rz, np.dot(Ry, Rx))

    return R

alpha_degrees = 30  # Rotation around X-axis
beta_degrees = 45   # Rotation around Y-axis
gamma_degrees = 60  # Rotation around Z-axis
r = rotate_points_euler((30,45,60))
r

array([[ 0.35355339, -0.5732233 ,  0.73919892],
       [ 0.61237244,  0.73919892,  0.28033009],
       [-0.70710678,  0.35355339,  0.61237244]])

In [54]:
R_WC = np.array([
    [0.83041423, 0.0085709, 0.16997286],
    [0.72704336, 0.77782549, 0.2303317],
    [0.46453981, 0.28336507, 0.43178532]
])

# Calculate the transpose of R_WC
R_WC_transpose = R_WC.T

# Calculate the product of R_WC_transpose and R_WC
product = R_WC_transpose @ R_WC 
prod2 = R_WC_transpose.dot(R_WC)
# Calculate the determinant of R_WC
determinant = np.linalg.det(R_WC)

product, prod2, determinant

(array([[1.43397708, 0.70426461, 0.50919049],
        [0.70426461, 0.68538172, 0.30296757],
        [0.50919049, 0.30296757, 0.26838203]]),
 array([[1.43397708, 0.70426461, 0.50919049],
        [0.70426461, 0.68538172, 0.30296757],
        [0.50919049, 0.30296757, 0.26838203]]),
 0.19652576697993326)

In [29]:
determinant = np.linalg.det(R_WC)
determinant

# Define a 3x3 orthogonal rotation matrix
R = np.array([
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 1]
])

# Calculate the product of R and its transpose
product = R @ R.T

# Create the identity matrix
I = np.eye(3)

# Check if the product is close to the identity matrix
is_orthogonal = np.allclose(product, I)

print(is_orthogonal)  # Should print: True
determinant = np.linalg.det(R)
print(determinant)

[[ 0 -1  0]
 [ 1  0  0]
 [ 0  0  1]]
True
1.0


In [24]:
R_WC = np.array([
    [0.83041423, 0.0085709, 0.16997286],
    [0.72704336, 0.77782549, 0.2303317],
    [0.46453981, 0.28336507, 0.43178532]
])

# Calculate the product of R_WC and its transpose
R_WC_transpose = R_WC.T
product = R_WC_transpose.dot(R_WC)
# Create the identity matrix
I = np.eye(3)
# Check if the product is close to the identity matrix
is_orthogonal = np.allclose(product, I)

print(is_orthogonal)

False


In [20]:
# Define a 3x3 orthogonal rotation matrix
R = np.array([
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 1]
])

# Calculate the product of R and its transpose
product = R @ R.T

# Create the identity matrix
I = np.eye(3)

# Check if the product is close to the identity matrix
is_orthogonal = np.allclose(product, I)

print(is_orthogonal)  # Should print: True
product

True


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [53]:
nR = np.array([[ 0.90698709, -0.41427723, -0.07582081],
        [ 0.40268484,  0.9057688 , -0.13201436],
        [ 0.12336666,  0.08920343,  0.98834377]])
# Calculate the product of R and its transpose
product = nR @ nR.T

# Create the identity matrix
I = np.eye(3)

# Check if the product is close to the identity matrix
is_orthogonal = np.allclose(product, I)

print(is_orthogonal)  # Should print: True


True


In [51]:
U, S, VT = np.linalg.svd(R_WC)
U, S, VT

(array([[-0.51178849,  0.81873394, -0.26028307],
        [-0.72857346, -0.57417108, -0.37350809],
        [-0.45525076, -0.0015218 ,  0.89036196]]),
 array([1.43312595, 0.51201607, 0.26782527]),
 array([[-0.81373381, -0.48850672, -0.31495788],
        [ 0.51118338, -0.85938482,  0.01221769],
        [-0.27663845, -0.15105928,  0.94902701]]))

In [50]:
# Perform SVD on the R_WC matrix
U, S, VT = np.linalg.svd(R_WC)

# Construct the closest rotation matrix R_closest
R_closest = U @ VT

# Ensure the determinant of R_closest is +1
if np.linalg.det(R_closest) < 0:
    # Multiply the last column of U by -1
    U[:, -1] *= -1
    # Reconstruct the rotation matrix R_closest
    R_closest = U @ VT

# Recalculate determinant to verify it is now +1
det_closest = np.linalg.det(R_closest)
R_closest, det_closest

(array([[ 0.90698709, -0.41427723, -0.07582081],
        [ 0.40268484,  0.9057688 , -0.13201436],
        [ 0.12336666,  0.08920343,  0.98834377]]),
 0.9999999999999988)

In [62]:
# The camera's forward vector in world coordinates is the third column of R_closest
camera_forward_vector = R_closest[:, 2]
# x, y, and z components of the camera's forward vector
x, y, z = camera_forward_vector
# Calculate the elevation angle theta in degrees
elevation_angle_rad = np.arctan2(z, np.sqrt(x**2 + y**2))
elevation_angle_deg = np.degrees(elevation_angle_rad)
print(elevation_angle_deg)

azimuth_angle_rad = np.arctan2(x, y)
azimuth_angle_deg = np.degrees(azimuth_angle_rad)
# Adjust the azimuth angle to be in the range [0, 360) degrees
azimuth_angle_from_north_deg = (azimuth_angle_deg + 360) % 360
print(azimuth_angle_from_north_deg)

81.24332184015904
209.87037097025765
